---

- name: GRAFANA | Installing dependencies
  apt:
    pkg: "{{ item }}"
    state: present
  with_items: "{{ required_libs }}"
  tags:
    skip_ansible_lint

- name: GRAFANA | Debian repo key on package cloud
  apt_key:
    url: "{{ grafana_key }}"

- name: GRAFANA | Debian grafana repo
  apt_repository:
    repo: "{{ grafana_repo }}"

- name: GRAFANA | Install grafana
  apt:
    pkg: grafana
    state: present

- name: Links grafana dir to /
  file:
    src: /etc/grafana
    dest: /grafana
    state: link
    force: yes
    owner: grafana
    group: grafana
